# fundamental concepts of tensors usig tensorflow
* intro to tensors
* information from tensors
* manipulating tensors
* tensors and numpy
* using @tf.function ( a way to speed up regular python functions)
* using gpus with tensorflow (or tpus) for faster numerical computaion

*italicized text*# intro to tensors

# import tensorflow
import tensorflow as tf
print(tf.__version__) # for checking the version of tensorflow

In [ ]:
## create tensors with tf.constant()
import tensorflow as tf
scalar  = tf.constant(7)
scalar

# commands - ctrl + MM  - markdown cell, ctrl + my - code cell
#            ctrl + MB - new cell
#            ctrl + shift + space - info about a command

## tensorflow has inbuilt modules which are able to read in data sorces such as how many diiferent images 
## and automatically convert them into tensors and later on the neural network model 
## will process these tensors

In [ ]:
# check no of dimensions of a tensor ( ndim stands for no of dimensions)
scalar.ndim

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector


In [20]:
# check dimensions of a vector
vector.ndim

NameError: name 'vector' is not defined

In [21]:

# create a matrix ( has more than 1 dimension)
import tensorflow as tf
matrix = tf.constant([[11, 7],
                      [7, 11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  7],
       [ 7, 11]])>

In [17]:
 pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [22]:
# create a matrix ( has more than 1 dimension)
import tensorflow as tf
matrix = tf.constant([[11, 7],
                      [7, 11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  7],
       [ 7, 11]])>

In [23]:
import tensorflw as tf
print(tf._version_)

ModuleNotFoundError: No module named 'tensorflw'

In [24]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [25]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [26]:
# check the number of dimnsions of a tensor ( ndim stands for number of dimensions)
scalar.ndim

0

In [27]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [28]:
# check the dimnsion of our vector
vector.ndim


1

In [29]:
# create a matrix(has more tahn 1 dimension)
matrix = tf.constant([[10, 7],
                    [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [30]:
#create anothe rmatrix
another_matrix = tf.constant([[10., 7.],
                             [3., 2.],
                             [8., 9.]], dtype=tf.float16)  # specify the data type with the dytpe parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [31]:
another_matrix.ndim

2

In [32]:
total no of dimensions = no of elements in shape

SyntaxError: invalid syntax (<ipython-input-32-4ed3bdee1d9a>, line 1)

In [33]:
#how to increase the number ofdiensions
# lets create a tensor
# a tensor
tensor = tf.constant([[[1, 2, 3],
                     [4, 5, 6]],
                     [[7, 8, 9],
                    [10, 11, 12]],
                     [[13, 14, 15],
                     [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [34]:
tensor.ndim

3

# what we've created so far

* Scalar : a single number
* Vector : a number with direction (eg wind speed and direction)
* matrix : a 2-dimensional array of numbers
* Tenso : an n-dimensional array of numbers ( when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)



In [35]:
#creating tensors with tf.variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [36]:
#lets try change one of the elements in our changeable vector
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [37]:
# trying .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [38]:
# try to change unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## creating random tensors
random tensors are tensors of some arbitrary size which contains random numbers

In [39]:
# create two random tensors
random_1= tf.random.Generator.from_seed(4) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1
random_2 = tf.random.Generator.from_seed(4)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

# they have come from a normal distrbution

# they are pseudo random numbers
# settig the seed -> create randm numbers but flavour them with x 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

####  shuffle the order of elements in a tensor

In [40]:
# shuffle a tensor ( valuable for when you  want to shuffle your data so that inherent order does not affect learning)
not_shuffled = tf.constant([[10, 7],
                          [3, 4],
                          [2, 5]])
not_shuffled.ndim

# shuffle our non-shffled tensor
tf.random.shuffle(not_shuffled)  # shuffles elements along its first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

In [41]:
# shuffle our non-shffled tensor
tf.random.shuffle(not_shuffled)  # shuffles elements along its first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [42]:
# using seed
# shuffle our non-shffled tensor
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [43]:
tf.random.shuffle(not_shuffled, seed = 42)  # gives differen result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [44]:
tf.random.set_seed(42) 
tf.random.shuffle(not_shuffled, seed = 42)  # gives same order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [45]:
# read through tensorflow documentation on random seed generator
# write 5 random tansors and shuffle them\

# operational and global level random seed

# main aim to shuffle the order of tensors is --> for classification neural networks -> any kind of images first may learn only one type of image

In [46]:
tf.random.shuffle(not_shuffled, seed = 42)  3 we get a different order each time

SyntaxError: invalid syntax (<ipython-input-46-b66b7616e12f>, line 1)

In [47]:
# using global radom seed 
tf.random.set_seed(42) # --> gives same order
tf.random.shuffle(not_shuffled, seed = 42)  

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### if we want our shuffled tensors to be in the same order , we have to use the global level random seed as well as the operational level random seed

### other ways to make tensors

In [48]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [49]:
# create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [50]:
### turn numpy arrays into tensors

main differencce NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU ( must faster for numerical computing)

SyntaxError: invalid syntax (<ipython-input-50-7d4003424638>, line 3)

In [51]:
# you can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector)  # non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [52]:
A = tf.constant(numpy_A)
A

# converted NumPy rray into a tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [53]:
# changing shape --> its shape is 24 if we want it into a 3-dimensional tensor
2*3*4
A = tf.constant(numpy_A, shape = (3, 8))  # 3 rows and 8 elements in one column
A  # this would be a tensor becoz it has got more than 1 dimension 
B= tf.constant(numpy_A)  # this is a vector
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

## Getting informatin from tensors

In [54]:
numpy_A.ndim

1

In [55]:
A.ndim

2

NumPy arrays are a very common form of representing numerical data --> can be converted into tensors

basic difference beteween numpy array and tensorflow tensor --> although they may store the same information here 
a tensor formmat can run on a gpu and finding pattrens in numerial data.


### want to get attribute s of tensors

When dealing with tensors want to be aware of the following attributes ->
* Shape - the length of each of the dimensions of a tensor
* Rank - the number of tensor dimensions . A scalar has rank 0, a vector has rank 1, a matrix has rank 2 , a tensor has rank n
* Axis or dimension - a particular dimension of a tensor --> tensor[0], tensor[:, 1]...
* Size - the total number of items in a tensor tf.size(tensor)

In [56]:
# Create a rank 4 matrix --> 4 dimensions
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

# when you pass a tensor into a neural network --> has to be in a certain shape and output also has to be in a certain shape

In [57]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [58]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [59]:
rank_4_tensor[0][1][3]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [60]:
# rank_4_tensor[0][1][4] -->gives error

In [61]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [63]:
# fget various attributes of our tensors
print("datatype of every element", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("elemnts along the 0 axis:",rank_4_tensor.shape[0])
print("elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elemnts in our tensor:", tf.size(rank_4_tensor))

datatype of every element <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
elemnts along the 0 axis: 2
elements along the last axis: 5
Total number of elemnts in our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [65]:

print("datatype of every element", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("elemnts along the 0 axis:",rank_4_tensor.shape[0])
print("elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elemnts in our tensor:", tf.size(rank_4_tensor))
print("Total number of elemnts in our tensor:", tf.size(rank_4_tensor).numpy())

datatype of every element <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
elemnts along the 0 axis: 2
elements along the last axis: 5
Total number of elemnts in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elemnts in our tensor: 120


### Indexing tensors

Tensors can be indexed like python lists

In [66]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [67]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2] # we seaparate the dimensions by commas

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [68]:
some_list[:1]

[1]

In [73]:
# get the first element from each dimension frome each index except for the final one
rank_4_tensor[:1, :1, :1,]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [74]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [77]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [78]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [83]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                           [3, 4]])
rank_2_tensor
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [98]:
some_list, some_list[-1], some_list[:-1]

([1, 2, 3, 4], 4, [1, 2, 3])

In [93]:
# get the last item of eah row of rank_2_matrix
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [97]:
rank_2_tensor[:, :-1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 3]])>

In [99]:
# if we want to add an extra dimension to this tensor
# we may need to alter the size of our tensors so that their shape line up

# add in extra dimension to our rank 2 tensor but information should be same
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [100]:
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [101]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [102]:
tf.expand_dims(rank_2_tensor, axis=1) #extra dimension u=in the middle

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

In [103]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [104]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

# how the numbers are stored changes just in changing dimension

### manipulating tensors (tensor operations)

In [110]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3,4]])
tensor + 10, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [111]:
tensor+=20
tensor
tensor-=20

In [112]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [113]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [114]:
# we can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [115]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

***Matrix Multiplication
In machine learning, matrix multiplication is one of the most common tensor operations
1. the inner dimnsions must match
2. the resulting matrix has shape of the outer dimensions

In [116]:
# matrix multiplication in tensorflow
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [117]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [118]:
tensor * tensor  # it is element wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [119]:
# matricx multiplication with python operator "@"
tensor @ tensor  used for matricx multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [120]:
tensor.shape

TensorShape([2, 2])

In [121]:
# with different shapes
# create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                [11, 12]])
X*Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]])>

In [122]:
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [124]:
#Matrix multilpy tensors
X @ Y
tf.multiply(X, Y)

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [126]:
# have to change the shape of either matrix
# or cretae new matrice sof same shape

# lets change the shape of y
tf.reshape(Y, shape = (2,3)), Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [128]:
X.shape, tf.reshape(Y, shape = (2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [130]:
# try to multiply X by reshaped y
X @ tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [132]:
tf.matmul(X, tf.reshape(Y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [135]:
# reshaping X
X.shape, Y.shape, tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

(TensorShape([3, 2]),
 TensorShape([3, 2]),
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>)

In [138]:
# can do the same wwith transpose
X, tf.transpose(X), tf.reshape(X ,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [ ]:
# transpose --> flips the axes rather than shuffling elements of tensors

In [139]:
# try matricx mult with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

** the dot product
matricx multis also referred to as the dot product
can perform mat mult using -->
* tf.matmul()
* tf.tensordot()

In [141]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [144]:
# perform the dot product on X and Y ( requires X or Y to be transposed)
# transposiing( flipping the axis) results in different outputs rather than reshaping ( reshuffling)

tf.tensordot(tf.transpose(X), Y, axes = 1), tf.matmul(tf.transpose(X), Y)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>)

In [145]:
# perfor mat mult bet x and y(transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [148]:
# perform mat ult bet x and y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [ ]:
# check the values of y, reshape Y, transposed Y
print("Norml Y\n", Y)
print("Y reshaped to (2, 3) : ")